# Generated by Django 3.0.8 on 2020-11-25 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='list',
            old_name='comleted',
            new_name='completed',
        ),
        migrations.AddField(
            model_name='list',
            name='deadline',
            field=models.DateTimeField(default=None),
        ),
    ]
